namespace :tests do
  desc "Run all tests"
  task :all => [:acceptance,:spec]

  desc "Run acceptance tests"
  task :acceptance do
    sh "rspec tests/acceptance/*.rb"
  end

  desc "Run specs"
  task :spec do
    sh "rspec tests/specs/*.rb"
  end
end
