require 'e-wallet/account'
require 'e-wallet/adder'
require 'e-wallet/exchange_rate'
require 'e-wallet/exceptions'
require 'e-wallet/exchanger'
require 'e-wallet/stock_price'
require 'e-wallet/stocker'
